import {test} from 'node:test';
import assert from 'node:assert/strict';
import {parseCalendar,validate} from '../lib/calendar.js';
import {options,render} from '../lib/render.js';
const cell=(date:string,count=0,level=0)=>`<div data-date="${date}" data-level="${level}" id="day-${date}"></div><tool-tip for="day-${date}">${count?count.toLocaleString('en-US'):'No'} contributions on a date.</tool-tip>`;
test('associa tooltip pelo id, ordena datas e soma contagens',()=>{const data=parseCalendar(cell('2026-09-03',1234,4)+cell('2026-09-01',2,1),'test','last-year','2026-09-04');assert.equal(data.total,1236);assert.equal(data.days[0].date,'2026-09-01');});
test('zero legítimo e erro estrutural não se confundem',()=>{assert.equal(parseCalendar(cell('2026-01-01'),'test','last-year').total,0);for(const html of ['', '<h1>Error</h1>',cell('2026-01-01').replace('No contributions','Unknown contributions')])assert.throws(()=>parseCalendar(html,'test','last-year'));});
test('ano bissexto completo e futuros neutros',()=>{let html='';for(let t=Date.UTC(2024,0,1);t<Date.UTC(2024,2,1);t+=86400000)html+=cell(new Date(t).toISOString().slice(0,10));const data=parseCalendar(html,'test','2024','2024-02-29');assert.equal(data.days.length,366);assert.equal(data.days.filter(d=>d.future).length,306);assert.equal(data.days.at(-1)!.date,'2024-12-31');assert.throws(()=>parseCalendar(cell('2024-01-01'),'test','2024','2024-02-29'));});
test('validação de usuário, período, dimensões e cor',()=>{validate('example-user','last-year');for(const user of ['../foo','a--b','<script>',''])assert.throws(()=>validate(user,'last-year'));assert.throws(()=>validate('foo','9999'));for(const query of ['width=4097','width=4000&height=4000','color=red','shape=triangle'])assert.throws(()=>options(new URLSearchParams(query)));});
test('renderiza temas, presets e formas com dias acessíveis',()=>{const data=parseCalendar(cell('2026-09-01',3,2),'test','last-year');for(const [width,height] of [[1290,2796],[1920,1080],[3840,2160]])for(const background of ['github','light','oled'])for(const shape of ['square','rounded','circle'])for(const layout of ['mosaic','weekly']){const svg=render(data,options(new URLSearchParams({width:String(width),height:String(height),background,shape,layout})));assert.match(svg,/2026-09-01: 3 contribuições/);assert.match(svg,/tabindex="0"/);assert.ok(!svg.includes('NaN'));}});
import {fetchCalendar,HttpError} from '../lib/calendar.js';
test('falhas de rede, usuário inexistente e status upstream',async()=>{const original=globalThis.fetch;try{for(const [status,expected] of [[404,404],[503,502]]){globalThis.fetch=async()=>new Response('',{status});await assert.rejects(fetchCalendar('test','last-year'),(e:unknown)=>e instanceof HttpError&&e.status===expected);}globalThis.fetch=async()=>{throw new Error('offline');};await assert.rejects(fetchCalendar('test','last-year'),/Não foi possível/);}finally{globalThis.fetch=original;}});

import contributionsHandler from '../api/contributions.js';
import graphHandler from '../api/graph.js';
import type {IncomingMessage,ServerResponse} from 'node:http';
async function callAPI(handler:typeof graphHandler,url:string){let body='';const res={statusCode:200,setHeader(){},end(chunk?:Buffer|string){body=String(chunk??'');}};await handler({url,method:'GET'} as IncomingMessage,res as unknown as ServerResponse);return {status:res.statusCode,body};}
test('APIs exigem username sem consultar GitHub e isolam perfis explícitos',async()=>{const original=globalThis.fetch;let calls=0;try{globalThis.fetch=async url=>{calls++;if(String(url).includes('.png'))return new Response('',{status:404});return new Response(cell('2026-09-01',String(url).includes('first-user')?2:7,2));};for(const handler of [contributionsHandler,graphHandler])for(const query of ['','?username=','?username=%20%20']){const result=await callAPI(handler,'/api/test'+query);assert.equal(result.status,400);assert.equal(JSON.parse(result.body).error,'Informe seu username do GitHub');}assert.equal(calls,0);for(const [username,total] of [['first-user',2],['second-user',7]] as const){const result=await callAPI(contributionsHandler,'/api/contributions?username='+username);assert.equal(result.status,200);assert.equal(JSON.parse(result.body).username,username);assert.equal(JSON.parse(result.body).total,total);const svg=await callAPI(graphHandler,'/graph?format=svg&username='+username);assert.equal(svg.status,200);assert.ok(svg.body.includes('Calendário de contribuições de '+username));assert.ok(!svg.body.includes(username==='first-user'?'second-user':'first-user'));}}finally{globalThis.fetch=original;}});
