import {render,options} from '../lib/render';
import {themes} from '../lib/themes';
import type {Calendar} from '../lib/calendar';
import type {Activity} from '../lib/activity';
export const activityDue=(visible:boolean,focused:boolean,loading:boolean,last:number,now:number)=>visible&&focused&&!loading&&now-last>=300000;
export function initLanding(demo:Calendar,open:()=>void,select:(id:string)=>void){
  const $=(s:string)=>document.querySelector<HTMLElement>(s)!;
  const preview=(theme:string,w:number,h:number)=>render(demo,options(new URLSearchParams({theme,width:String(w),height:String(h),layout:w>h?'weekly':'mosaic',avatar:'1'}))).replaceAll('tabindex="0"','tabindex="-1"');
  const swap=(el:HTMLElement,svg:string)=>{const old=el.firstElementChild?.cloneNode(true) as HTMLElement|undefined;el.innerHTML=svg;if(old&&!matchMedia('(prefers-reduced-motion: reduce)').matches){old.classList.add('outgoing');old.setAttribute('aria-hidden','true');el.append(old);old.animate([{opacity:1},{opacity:0}],{duration:200}).finished.finally(()=>old.remove());}};
  function show(theme:string){swap($('#hero-image'),preview(theme,1290,2796));swap($('#desktop-image'),preview(theme,1920,1080));document.querySelectorAll<HTMLElement>('[data-demo]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.demo===theme)));}
  $('#landing-gallery').innerHTML=['Sólidos','Gradientes','Texturas'].map(group=>`<div class="gallery-group"><h3>${group}</h3><div class="gallery-grid">${themes.filter(t=>t.group===group).map(t=>`<article><button class="gallery-preview" data-demo="${t.id}" aria-label="Experimentar ${t.name}" aria-pressed="false"><span aria-hidden="true">${preview(t.id,640,400)}</span></button><div class="gallery-caption"><strong>${t.name}</strong><button data-use="${t.id}">Usar este tema ↗</button></div></article>`).join('')}</div></div>`).join('');
  show('github');
  document.querySelectorAll<HTMLElement>('[data-demo]').forEach(b=>b.addEventListener('click',()=>show(b.dataset.demo!)));
  document.querySelectorAll<HTMLElement>('[data-create]').forEach(b=>b.addEventListener('click',open));
  document.querySelectorAll<HTMLElement>('[data-use]').forEach(b=>b.addEventListener('click',()=>{select(b.dataset.use!);open();}));
  const reveal=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){if(!matchMedia('(prefers-reduced-motion: reduce)').matches)e.target.animate([{opacity:0,transform:'translateY(8px)'},{opacity:1,transform:'translateY(0)'}],{duration:200});reveal.unobserve(e.target);}}),{threshold:.1});document.querySelectorAll('.reveal').forEach(e=>reveal.observe(e));
  let visible=false,loading=false,last=-Infinity,snapshot:Activity|undefined,timer:ReturnType<typeof setTimeout>|undefined;
  const node=(tag:string,text:string)=>{const n=document.createElement(tag);n.textContent=text;return n;};
  function paint(data:Activity){const content=$('#activity-content');content.replaceChildren();const metrics=node('div','');metrics.className='activity-metrics';metrics.append(node('span',`${data.stars.toLocaleString('pt-BR')} stars`),node('span',`${data.forks.toLocaleString('pt-BR')} forks`));content.append(metrics,node('h3','Últimos commits'));const list=document.createElement('ol');list.className='commit-list';for(const c of data.commits){const li=document.createElement('li'),link=node('a',c.message) as HTMLAnchorElement;link.href=`https://github.com/mvtiburcio/git-calendar-wallpaper/commit/${c.sha}`;li.append(node('code',c.sha.slice(0,7)),link,node('small',`${c.author} · ${new Date(c.date).toLocaleString('pt-BR')}`));list.append(li);}content.append(data.commits.length?list:node('p','Nenhum commit disponível.'),node('h3','Quem contribui'));const people=document.createElement('div');people.className='contributors';for(const c of data.contributors){const a=node('a','') as HTMLAnchorElement;a.href=`https://github.com/${encodeURIComponent(c.login)}`;const img=document.createElement('img');img.src=c.avatar;img.alt='';img.loading='lazy';img.width=32;img.height=32;img.addEventListener('error',()=>img.hidden=true);a.append(img,node('span','@'+c.login));people.append(a);}content.append(data.contributors.length?people:node('p','Ainda sem contribuidores listados.'));}
  async function refresh(){if(!activityDue(visible,document.visibilityState==='visible',loading,last,Date.now()))return;clearTimeout(timer);loading=true;last=Date.now();if(!snapshot)$('#activity-status').textContent='Consultando atividade pública…';try{const response=await fetch('/api/project-activity',{signal:AbortSignal.timeout(10000)});if(!response.ok)throw Error();const data:Activity=await response.json();snapshot=data;paint(data);$('#activity-status').textContent=`Atualização automática · consultado às ${new Date(data.fetchedAt).toLocaleTimeString('pt-BR')} · intervalo de 5 minutos`;}catch{$('#activity-status').textContent=snapshot?`Dados desatualizados · última consulta ${new Date(snapshot.fetchedAt).toLocaleString('pt-BR')}. Tentaremos novamente em 5 minutos.`:'Atividade indisponível no momento. Consulte o repositório no GitHub.';}finally{loading=false;timer=setTimeout(()=>void refresh(),Math.max(0,300000-(Date.now()-last)));}}
  new IntersectionObserver(entries=>{visible=entries[0].isIntersecting;void refresh();},{threshold:.05}).observe($('#open-source'));
  document.addEventListener('visibilitychange',()=>void refresh());
}
