import './style.css';
import {options,render} from '../lib/render';
import {themes} from '../lib/themes';
import type {Calendar} from '../lib/calendar';
import {devices,shortcutPrompt,LatestRequest} from './setup';
const demoDays=Array.from({length:365},(_,i)=>({date:new Date(Date.UTC(2025,8,5+i)).toISOString().slice(0,10),count:i%7<2?0:(i*17)%32,level:i%7<2?0:1+(i*7)%4,future:false}));
const demo:Calendar={username:'seu-usuario',period:'last-year',days:demoDays,total:demoDays.reduce((s,d)=>s+d.count,0),fetchedAt:''};
const years=Array.from({length:new Date().getUTCFullYear()-2007},(_,i)=>new Date().getUTCFullYear()-i);
const labels=['Seu perfil','Sua tela','Seu estilo','Usar wallpaper'];
const arrow='<span aria-hidden="true">↗</span>';
document.querySelector('#app')!.innerHTML=`
<header class="site-header"><a class="brand" href="/" aria-label="Git Calendar Wallpaper, início"><span class="brand-icon" aria-hidden="true">▦</span>git calendar<span class="brand-suffix">wallpaper</span></a><a class="source-link" href="https://github.com/mvtiburcio/git-calendar-wallpaper" target="_blank" rel="noopener">Código aberto ${arrow}</a></header>
<main>
<section id="home" class="hero"><div class="hero-copy"><span class="eyebrow"><i></i> FEITO COM O SEU GITHUB</span><h1>Seu código.<br>Seu ritmo.<br><span>Sua tela.</span></h1><p>Transforme suas contribuições em um wallpaper com a sua cara. Personalize, baixe e deixe atualizar.</p><button id="start" class="primary">Criar meu wallpaper ${arrow}</button><div class="hero-note">Sem login · Sem marca-d’água · Código aberto</div><div class="hero-swatches" aria-label="Experimentar tema na demonstração">${['github','aurora','paper'].map((id,i)=>`<button data-demo="${id}" aria-pressed="${i===0}">${themes.find(t=>t.id===id)!.name}</button>`).join('')}</div></div><div class="hero-art"><div class="phone hero-phone"><div id="hero-image" aria-hidden="true"></div><div class="mock-clock" aria-hidden="true"><small>Seu próximo capítulo</small><b>09:41</b></div><div class="phone-island" aria-hidden="true"></div><div class="phone-bottom" aria-hidden="true"></div></div><p class="demo-caption">Uma prévia do que pode ser seu.<br>Calendário demonstrativo.</p></div></section>
<section id="wizard" hidden aria-label="Criar wallpaper"><div class="wizard-top"><button id="home-back" class="text-button">← Início</button><span class="eyebrow">DO PERFIL PARA SUA TELA</span></div><ol class="steps" aria-label="Progresso">${labels.map((label,i)=>`<li><span class="step-number">${i+1}</span><span>${label}</span></li>`).join('')}</ol>
<div class="editor"><aside class="preview-side"><div class="preview-toolbar"><span>PRÉVIA</span><button id="expand" class="text-button" aria-expanded="false">Ampliar</button></div><div id="preview-frame" class="phone"><div id="preview" tabindex="0" aria-label="Calendário. Use as setas para explorar os dias."></div><div class="mock-clock" aria-hidden="true"><small>Seu GitHub, todos os dias</small><b>09:41</b></div><div class="phone-island" aria-hidden="true"></div></div><p id="preview-info" class="preview-info">Seu calendário aparece aqui.</p><p id="day-info" class="hint" aria-live="polite"></p></aside>
<div class="controls"><form id="settings" novalidate>
<section class="step-panel" data-step="0"><p class="eyebrow">PASSO 1 DE 4</p><h2 tabindex="-1">Vamos começar por você.</h2><p class="intro">Qual perfil do GitHub vai na sua tela?</p><label for="username">Username do GitHub</label><div class="search-row"><div class="username-wrap"><span aria-hidden="true">@</span><input id="username" name="username" value="mvtiburcio" maxlength="39" autocomplete="off" spellcheck="false" aria-describedby="profile-error"></div><button id="search" type="button">Buscar perfil</button></div><p id="profile-error" class="error" role="alert"></p><div id="profile-result" hidden></div><p class="privacy-note">Só usamos informações públicas. Para incluir contagens privadas, ative <strong>Include private contributions on my profile</strong> no GitHub.</p></section>
<section class="step-panel" data-step="1" hidden><p class="eyebrow">PASSO 2 DE 4</p><h2 tabindex="-1">Onde ele vai morar?</h2><p class="intro">Escolha a tela. A resolução fica por nossa conta.</p><div class="segments" id="device-kind" aria-label="Tipo de aparelho"><button type="button" data-device="iphone" aria-pressed="true">iPhone</button><button type="button" data-device="mobile" aria-pressed="false">Outro celular</button><button type="button" data-device="desktop" aria-pressed="false">Desktop</button></div><div id="iphone-options"><label for="iphone">Modelo do iPhone</label><select id="iphone"><option value="">Selecione seu modelo</option>${devices.map((d,i)=>`<option value="${i}">${d.name}</option>`).join('')}<option value="custom">Outro modelo / tamanho personalizado</option></select><p class="hint">Não sabe o modelo? Veja em Ajustes › Geral › Sobre.</p></div><div id="desktop-options" hidden><label for="desktop">Resolução</label><select id="desktop"><option value="1920,1080">Full HD · 1920 × 1080</option><option value="3840,2160">4K · 3840 × 2160</option><option value="custom">Personalizada</option></select></div><details id="dimensions-details"><summary>Dimensões personalizadas</summary><div class="pair"><label>Largura<input name="width" type="number" min="320" max="4096" value="1290"></label><label>Altura<input name="height" type="number" min="320" max="4096" value="2796"></label></div><p class="hint">Até 4096 px por lado e 9 milhões de pixels.</p></details><p id="size-error" class="error" role="alert"></p></section>
<section class="step-panel" data-step="2" hidden><p class="eyebrow">PASSO 3 DE 4</p><h2 tabindex="-1">Agora, a sua cara.</h2><p class="intro">Comece com um tema. Mude o que quiser.</p><input type="hidden" name="theme" value="github"><div class="theme-tabs" aria-label="Categorias de temas">${['Todos','Sólidos','Gradientes','Texturas'].map((g,i)=>`<button type="button" data-category="${g}" aria-pressed="${i===0}">${g}</button>`).join('')}</div><div id="theme-grid" class="theme-grid"></div><label class="check"><input name="avatar" type="checkbox" checked> Mostrar minha foto no wallpaper</label><details class="advanced"><summary>Personalizar do meu jeito <span>+</span></summary><div class="pair"><label>Contribuições<input name="color" type="color" value="#39d353"></label><label>Fundo<input name="bg" type="color" value="#0d1117"></label></div><div class="pair"><label>Segunda cor<input name="end" type="color" value="#0d1117"></label><label>Direção do gradiente<input name="angle" type="range" min="0" max="360" value="135"></label></div><div class="pair"><label>Textura<select name="texture"><option value="none">Sem textura</option><option value="paper">Papel</option><option value="dots">Pontilhado</option><option value="topo">Topográfico</option></select></label><label>Intensidade<input name="intensity" type="range" min="0" max="0.35" step="0.01" value="0.12"></label></div><div class="pair"><label>Células<select name="shape"><option value="rounded">Arredondadas</option><option value="square">Quadradas</option><option value="circle">Circulares</option></select></label><label>Organização<select name="layout"><option value="mosaic">Mosaico</option><option value="weekly">Semanal</option></select></label></div><div class="pair"><label>Escala<input name="scale" type="range" min="0.6" max="1.15" step="0.01" value="1"></label><label>Posição vertical<input name="position" type="range" min="0" max="1" step="0.01" value="0.5"></label></div><label>Período<select name="period"><option value="last-year">Últimos 12 meses</option>${years.map(y=>`<option>${y}</option>`).join('')}</select></label></details><p id="style-error" class="error" role="alert"></p></section>
<section class="step-panel" data-step="3" hidden><p class="eyebrow">PASSO 4 DE 4</p><h2 tabindex="-1">Pronto para sua tela.</h2><p class="intro">Seu calendário, do seu jeito. Agora é só usar.</p><div class="downloads"><button id="png" type="button" class="primary">Baixar PNG ↓</button><button id="svg" type="button">Baixar SVG ↓</button></div><button id="copy-url" type="button" class="wide">Copiar URL da imagem ${arrow}</button><div class="install"><h3>Criar com Apple Intelligence</h3><p>Se o seu app Atalhos permite criar por descrição, a instrução já está pronta.</p><div class="pair"><label>Atualizar todo dia às<input id="time" type="time" value="06:00"></label><label>Aplicar em<select id="target"><option value="lock">Tela bloqueada</option><option value="home">Tela inicial</option><option value="both">As duas telas</option></select></label></div><ol class="install-steps"><li>Copie a instrução abaixo.</li><li>Abra Atalhos e cole na criação por descrição.</li><li>Revise e execute uma vez para testar e autorizar.</li></ol><button id="copy-prompt" type="button" class="primary wide">Copiar instrução pronta ${arrow}</button><details><summary>Ver instrução</summary><textarea id="prompt" readonly aria-label="Instrução para Apple Intelligence"></textarea></details><p class="hint">Disponibilidade depende do iPhone, idioma e versão do sistema. A criação acontece no app Atalhos, não neste site.</p><details><summary>Meu iPhone não tem esse recurso</summary><ol class="manual"><li>No app Atalhos, crie um atalho com a URL copiada em <strong>Copiar URL da imagem</strong>.</li><li>Adicione <strong>Obter Conteúdo de URL</strong> (GET), seguido de <strong>Definir Foto do Papel de Parede</strong>, usando a imagem recebida.</li><li>Escolha a tela e desative a prévia, se disponível. Execute uma vez para testar e conceder permissões.</li><li>Em Automação, configure execução diária por Hora do Dia e selecione esse atalho. Use execução imediata quando disponível.</li></ol><p class="hint">Os nomes variam entre versões. Em erro de rede, mantenha a imagem anterior.</p></details></div></section>
<div class="navigation"><button id="back" type="button" class="text-button">← Voltar</button><button id="next" type="submit" class="primary">Continuar →</button></div></form><p id="notice" class="notice" role="status" aria-live="polite"></p><p class="cache-note">Dados públicos do GitHub · Atualização em até 1 hora</p></div></div></section>
</main><footer><span>Feito para refletir seu trabalho. Não para contar só uma parte.</span><a href="https://github.com/mvtiburcio/git-calendar-wallpaper">GitHub ${arrow}</a></footer>`;
const $=<T extends HTMLElement=HTMLElement>(selector:string)=>document.querySelector<T>(selector)!;
const form=$<HTMLFormElement>('#settings'), request=new LatestRequest();
const field=(name:string)=>form.elements.namedItem(name) as HTMLInputElement|HTMLSelectElement;
let calendar:Calendar|undefined,step=0,device='iphone',loading=false,downloading=false,dayIndex=0;
const notice=(text:string)=>{$('#notice').textContent=text;};
function parameters(){const p=new URLSearchParams([...new FormData(form)].map(([k,v])=>[k,String(v)]));p.set('avatar',(field('avatar') as HTMLInputElement).checked?'1':'0');return p;}
function graphURL(format='png'){const p=parameters();p.set('format',format);return location.origin+'/graph?'+p;}
const cleanPreview=(svg:string)=>svg.replaceAll('tabindex="0"','tabindex="-1"');
function demoRender(theme='github'){return cleanPreview(render(demo,options(new URLSearchParams({theme,avatar:'1'}))));}
$('#hero-image').innerHTML=demoRender();
function refreshButtons(){const valid=!!calendar&&calendar.username===field('username').value&&calendar.period===field('period').value&&!loading;
  $<HTMLButtonElement>('#next').disabled=loading||(step===0&&!valid);$<HTMLButtonElement>('#search').disabled=loading;
  for(const id of ['png','svg','copy-url','copy-prompt'])$<HTMLButtonElement>('#'+id).disabled=!valid||downloading;
}
function renderThemes(){const selected=field('theme').value;$('#theme-grid').innerHTML=themes.map(t=>`<button type="button" class="theme" data-theme="${t.id}" data-group="${t.group}" aria-pressed="${t.id===selected}"><span class="theme-picture" aria-hidden="true">${cleanPreview(render(demo,options(new URLSearchParams({theme:t.id,width:"480",height:"400",avatar:"0"}))))}</span><span>${t.name}<i aria-hidden="true">${t.id===selected?'✓':''}</i></span></button>`).join('');}
renderThemes();
function updatePrompt(){try{$<HTMLTextAreaElement>('#prompt').value=shortcutPrompt(graphURL(),$<HTMLInputElement>('#time').value,$<HTMLSelectElement>('#target').value);}catch(e){notice((e as Error).message);}}
function draw(animate=false){
  try{const o=options(parameters());const data=calendar??demo;const target=$('#preview');
    const old=animate?target.firstElementChild?.cloneNode(true) as SVGElement|undefined:undefined;
    target.innerHTML=cleanPreview(render(data,o));
    if(old&&!matchMedia('(prefers-reduced-motion: reduce)').matches){old.classList.add('outgoing');old.setAttribute('aria-hidden','true');target.append(old);old.animate([{opacity:1},{opacity:0}],{duration:200,easing:'cubic-bezier(.16,1,.3,1)'}).finished.finally(()=>old.remove());}
    $('#preview-frame').classList.toggle('landscape',o.width>=o.height);
    $('#preview-info').textContent=calendar?`@${calendar.username} · ${calendar.total.toLocaleString('pt-BR')} contribuições · ${o.width} × ${o.height}`:'Demonstração. Busque seu perfil para ver os dados reais.';
    $('#style-error').textContent='';$('#size-error').textContent='';updatePrompt();refreshButtons();return true;
  }catch(e){$(step===1?'#size-error':'#style-error').textContent=(e as Error).message;return false;}
}
function go(next:number){step=next;document.querySelectorAll<HTMLElement>('.step-panel').forEach((panel,i)=>{panel.hidden=i!==step;});document.querySelectorAll('.steps li').forEach((li,i)=>{li.classList.toggle('active',i===step);li.classList.toggle('complete',i<step);if(i===step)li.setAttribute('aria-current','step');else li.removeAttribute('aria-current');});$('#next').hidden=step===3;$('#back').textContent=step===0?'← Início':'← Voltar';notice('');refreshButtons();const heading=$<HTMLElement>(`[data-step="${step}"] h2`);heading.focus({preventScroll:true});if(matchMedia('(max-width: 760px)').matches)$('.controls').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'});updatePrompt();}
async function search(){
  const username=field('username').value.trim(),period=field('period').value;field('username').value=username;
  const current=request.start();loading=true;refreshButtons();$('#profile-error').textContent='';notice('Buscando seu calendário…');
  try{const response=await fetch('/api/contributions?'+new URLSearchParams({username,period}),{signal:current.signal});const data=await response.json();if(!current.current())return;if(!response.ok)throw new Error(data.error??'Não foi possível buscar o perfil.');calendar=data;
    const result=$('#profile-result');result.replaceChildren();const avatar=document.createElement('img');avatar.src=data.avatarData??'data:image/svg+xml,'+encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="64" height="64"><rect width="64" height="64" rx="32" fill="#334"/><text x="32" y="42" fill="#eee" font-size="32" text-anchor="middle">${username[0].toUpperCase()}</text></svg>`);avatar.alt='Foto de '+username;const text=document.createElement('div'),name=document.createElement('strong'),count=document.createElement('span');name.textContent='@'+username;count.textContent=data.total.toLocaleString('pt-BR')+' contribuições no período';text.append(name,count);result.append(avatar,text);result.hidden=false;notice('Perfil encontrado. Pode continuar.');draw(true);
  }catch(e){if(!current.current())return;calendar=undefined;draw();$('#profile-result').hidden=true;$('#profile-error').textContent=(e as Error).message;if(step===2)$('#style-error').textContent=(e as Error).message;notice('Não foi possível carregar. Confira o perfil e tente novamente.');}
  finally{if(current.current()){loading=false;refreshButtons();}}
}
$('#start').addEventListener('click',()=>{$('#home').hidden=true;$('#wizard').hidden=false;draw();go(0);});
const home=()=>{$('#wizard').hidden=true;$('#home').hidden=false;$('#start').focus();};
$('#home-back').addEventListener('click',home);$('#back').addEventListener('click',()=>step===0?home():go(step-1));
$('#search').addEventListener('click',()=>void search());
field('username').addEventListener('input',()=>{request.cancel();loading=false;calendar=undefined;$('#profile-result').hidden=true;$('#profile-error').textContent='';notice('Busque o perfil para continuar.');draw();refreshButtons();});
form.addEventListener('submit',e=>{e.preventDefault();if(step===0&&(!calendar||calendar.username!==field('username').value)){void search();return;}if(loading)return;if(step===1&&device==='iphone'&&!$<HTMLSelectElement>('#iphone').value){$('#size-error').textContent='Selecione um modelo ou escolha tamanho personalizado.';$('#iphone').focus();return;}if(!draw())return;if(!calendar||calendar.period!==field('period').value){notice('Busque o calendário antes de continuar.');return;}if(step<3)go(step+1);});
function dimensions(width:number,height:number){field('width').value=String(width);field('height').value=String(height);field('layout').value=width>=height?'weekly':'mosaic';draw();}
$('#device-kind').addEventListener('click',e=>{const button=(e.target as Element).closest<HTMLButtonElement>('[data-device]');if(!button)return;device=button.dataset.device!;document.querySelectorAll<HTMLElement>('[data-device]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));$('#iphone-options').hidden=device!=='iphone';$('#desktop-options').hidden=device!=='desktop';$<HTMLDetailsElement>('#dimensions-details').open=device==='mobile';if(device==='desktop'){const value=$<HTMLSelectElement>('#desktop').value;if(value!=='custom'){const [w,h]=value.split(',').map(Number);dimensions(w,h);}}else dimensions(1290,2796);if(device==='iphone')$<HTMLSelectElement>('#iphone').value='';});
$('#iphone').addEventListener('change',()=>{const value=$<HTMLSelectElement>('#iphone').value;$<HTMLDetailsElement>('#dimensions-details').open=value==='custom';if(value&&value!=='custom'){const d=devices[+value];dimensions(d.width,d.height);}});
$('#desktop').addEventListener('change',()=>{const value=$<HTMLSelectElement>('#desktop').value;$<HTMLDetailsElement>('#dimensions-details').open=value==='custom';if(value!=='custom'){const [w,h]=value.split(',').map(Number);dimensions(w,h);}});
for(const name of ['width','height'])field(name).addEventListener('input',()=>{if(device==='iphone')$<HTMLSelectElement>('#iphone').value='custom';if(device==='desktop')$<HTMLSelectElement>('#desktop').value='custom';});
$('#theme-grid').addEventListener('click',e=>{const button=(e.target as Element).closest<HTMLButtonElement>('[data-theme]');if(!button)return;const t=themes.find(t=>t.id===button.dataset.theme)!;field('theme').value=t.id;field('bg').value=t.bg;field('end').value=t.end;field('color').value=t.accent;field('texture').value=t.texture;document.querySelectorAll<HTMLElement>('[data-theme]').forEach(b=>{b.setAttribute('aria-pressed',String(b===button));b.querySelector('i')!.textContent=b===button?'✓':'';});draw(true);});
document.querySelector('.theme-tabs')!.addEventListener('click',e=>{const button=(e.target as Element).closest<HTMLButtonElement>('[data-category]');if(!button)return;document.querySelectorAll<HTMLElement>('[data-category]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));document.querySelectorAll<HTMLElement>('[data-theme]').forEach(b=>b.hidden=button.dataset.category!=='Todos'&&b.dataset.group!==button.dataset.category);});
form.addEventListener('input',e=>{const target=e.target as HTMLInputElement;if(target.name&&target.name!=='username'&&target.name!=='period')draw();});
field('period').addEventListener('change',()=>void search());
$('#expand').addEventListener('click',()=>{const expanded=$('.preview-side').classList.toggle('expanded');$('#expand').setAttribute('aria-expanded',String(expanded));$('#expand').textContent=expanded?'Reduzir':'Ampliar';});
for(const format of ['png','svg'])$('#'+format).addEventListener('click',async()=>{downloading=true;refreshButtons();notice('Preparando sua imagem…');const username=calendar!.username;try{const response=await fetch(graphURL(format));if(!response.ok)throw new Error((await response.json()).error);const href=URL.createObjectURL(await response.blob()),link=document.createElement('a');link.href=href;link.download=`${username}-calendar.${format}`;link.click();setTimeout(()=>URL.revokeObjectURL(href),10000);notice('Imagem pronta. Confira seus downloads.');}catch(e){notice((e as Error).message);}finally{downloading=false;refreshButtons();}});
async function copy(text:string,success:string){try{await navigator.clipboard.writeText(text);notice(success);}catch{notice('Não foi possível copiar automaticamente. A instrução pode ser selecionada em “Ver instrução”.');}}
$('#copy-url').addEventListener('click',()=>void copy(graphURL(),'URL copiada. Ela acompanha as atualizações do GitHub.'));
$('#copy-prompt').addEventListener('click',()=>{try{const text=shortcutPrompt(graphURL(),$<HTMLInputElement>('#time').value,$<HTMLSelectElement>('#target').value);void copy(text,'Instrução copiada. Agora cole na criação por descrição do app Atalhos.');}catch(e){notice((e as Error).message);}});
for(const id of ['time','target'])$('#'+id).addEventListener('input',updatePrompt);
document.querySelectorAll<HTMLElement>('[data-demo]').forEach(button=>button.addEventListener('click',()=>{$('#hero-image').innerHTML=demoRender(button.dataset.demo);document.querySelectorAll('[data-demo]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));}));
$('#preview').addEventListener('pointerover',e=>{const label=(e.target as Element).closest('[aria-label]')?.getAttribute('aria-label');if(label&&label.includes(':'))$('#day-info').textContent=label;});
$('#preview').addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))return;e.preventDefault();const cells=[...$('#preview').querySelectorAll<SVGElement>('[tabindex]')];dayIndex=Math.max(0,Math.min(cells.length-1,dayIndex+(e.key==='ArrowLeft'||e.key==='ArrowUp'?-1:1)));cells.forEach(c=>c.classList.remove('day-focus'));cells[dayIndex]?.classList.add('day-focus');$('#day-info').textContent=cells[dayIndex]?.getAttribute('aria-label')??'';});
